### ISSUE TITLE
BUG: `+scss` doesn't support `&` and nested SCSS

### ISSUE THREAD

**Issue by Riernar** [Kurohyou-Studios/k-scaffold#96]
### Description

The following SCSS crashes the `.scss` mixin, be it with the `+scss.` direct input, or `+scss` and an `include` inside:

```scss
+scss.
    // SCSS for rolls
    .roller {
        padding: 0.2rem;
        border: 0.1rem solid black;
        border-radius: 0.5rem;

        &::before {
            font-family: "dicefontd6";
            content: "L";
        }
    }
```

Not using the `&` symbol works properly:

```scss
+scss.
    // SCSS for rolls
    .roller {
        padding: 0.2rem;
        border: 0.1rem solid black;
        border-radius: 0.5rem;
    }

    .roller::before {
        font-family: "dicefontd6";
        content: "L";
    }
```

### Environment
```
$ npm list @kurohyou/k-scaffold
sr4@0.1 /home/quentin/dev/jdr.d/sr4-sheet
└── @kurohyou/k-scaffold@2.2.2
```
